### ISSUE TITLE
Don't send click events after controller was paused

### ISSUE THREAD

**Issue by hedshafran** [nu-art/cyborg-core#11]
`FATAL EXCEPTION: main
                                                              Process: com.hearWeGo, PID: 13907
                                                              com.nu.art.core.exceptions.runtime.ImplementationMissingException: In order to use the stack, this view must be a contained within a StackController
                                                                  at com.nu.art.cyborg.core.CyborgController.getStack(CyborgController.java:239)
                                                                  at com.nu.art.cyborg.core.CyborgController.createNewLayerBuilder(CyborgController.java:558)
                                                                  at com.hearWeGo.ui.Controller_Menu.onRecyclerItemClicked(Controller_Menu.java:88)
                                                                  at com.nu.art.cyborg.core.CyborgControllerBase$ActionDelegator.onRecyclerItemClicked(CyborgControllerBase.java:161)
                                                                  at com.nu.art.cyborg.core.CyborgAdapter$CyborgRecyclerAdapter.onClick(CyborgAdapter.java:408)
                                                                  at android.view.View.performClick(View.java:5204)
                                                                  at android.view.View$PerformClick.run(View.java:21153)
                                                                  at android.os.Handler.handleCallback(Handler.java:739)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:148)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                  at java.lang.reflect.Method.invoke(Native Method)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)`

**Comment by TacB0sS** [comment]
Merged the CyborgControllerBase into CyborgController, and added a condition that only if the controller is in resumed state, events will be delivered!
